Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$FakeManagerRequestFilter'

TestSessionController:
  extensions:
    - FakeTestSessionControllerExtension

TestSessionEnvironment:
  extensions:
    - FakeTestSessionEnvironmentExtension